server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true     # 保留这行
    allow-circular-references: true   # 加上这行，直接关闭所有检测

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.example.shop.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
